# Data  Analysis using python

## Array programming with numpy
### Array  Creation and Properties 

In [1]:
import numpy as np

In [2]:
a=np.arange(11)
b=np.arange(25)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
a=np.arange(10).reshape(2,5)

In [6]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
a=np.arange(15).reshape(3,5)

In [8]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
print(a.ndim)

2


In [10]:
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [11]:
s=np.arange(10).reshape(2,5)

In [12]:
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
print(s.ndim)
print(s.shape)
print(s.size)
print(s.dtype)
print(s.itemsize)
print(type(s))

2
(2, 5)
10
int32
4
<class 'numpy.ndarray'>


In [14]:
help(s)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [15]:
h=np.array([23.0,24.0,25.0,26.0])

In [16]:
print(h)

[23. 24. 25. 26.]


In [17]:
print(h.dtype)

float64


In [18]:
print(type(h))

<class 'numpy.ndarray'>


In [19]:
r=np.eye(15)

In [20]:
dtype=np.float64

In [21]:
r

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [22]:
#linspace(and logspace) create arrays with every space in log
i=np.linspace(-1,2,15,endpoint=True)

In [23]:
print(i)

[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [24]:
#endpoint is false
i=np.linspace(-1,2,15,endpoint=False)

In [25]:
i

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ,
        1.2,  1.4,  1.6,  1.8])

In [26]:
#change start,end,count values
i=np.linspace(-2,3,25,endpoint=True)

In [27]:
i

array([-2.        , -1.79166667, -1.58333333, -1.375     , -1.16666667,
       -0.95833333, -0.75      , -0.54166667, -0.33333333, -0.125     ,
        0.08333333,  0.29166667,  0.5       ,  0.70833333,  0.91666667,
        1.125     ,  1.33333333,  1.54166667,  1.75      ,  1.95833333,
        2.16666667,  2.375     ,  2.58333333,  2.79166667,  3.        ])

In [28]:
k=np.logspace(-1,2,15,endpoint=True,base=10)

In [29]:
print(k)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [30]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [31]:
u=np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

In [32]:
u

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
u=np.fromfunction(lambda i,j:i==j,(3,4),dtype=int)

In [34]:
u

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

## Array operations

In [35]:
a=np.arange(12).reshape(3,4)

In [36]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
a=np.arange(100).reshape(10,10)

In [38]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
p=np.arange(10).reshape(2,5)

In [40]:
p

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
p*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [42]:
p+p

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [43]:
p*p

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [44]:
print(p)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [47]:
q=p.transpose()

In [48]:
q

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [49]:
p@q

array([[ 30,  80],
       [ 80, 255]])

In [50]:
print(p)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [51]:
p.sum(axis=1)

array([10, 35])

In [52]:
a.sum()

4950

In [53]:
#sum rows
p.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [54]:
p.sum()

45

In [55]:
print(a.min(),a.max())

0 99


## Universal functions 

In [56]:
r=p*np.pi/12.0

In [57]:
print(r)

[[0.         0.26179939 0.52359878 0.78539816 1.04719755]
 [1.30899694 1.57079633 1.83259571 2.0943951  2.35619449]]


In [58]:
e=np.sin(r)

In [59]:
print(e)

[[0.         0.25881905 0.5        0.70710678 0.8660254 ]
 [0.96592583 1.         0.96592583 0.8660254  0.70710678]]


In [60]:
e=np.cos(r)

In [61]:
print(e)

[[ 1.00000000e+00  9.65925826e-01  8.66025404e-01  7.07106781e-01
   5.00000000e-01]
 [ 2.58819045e-01  6.12323400e-17 -2.58819045e-01 -5.00000000e-01
  -7.07106781e-01]]


In [62]:
d=r+e

In [63]:
print(d)

[[1.         1.22772521 1.38962418 1.49250494 1.54719755]
 [1.56781598 1.57079633 1.57377667 1.5943951  1.64908771]]


## Array Slicing:Accessing Subarrays 

In [64]:
a=np.arange(15)

In [65]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
shri=np.arange(20)

In [67]:
shri

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
even=shri[0:20:2]

In [69]:
print(even)

[ 0  2  4  6  8 10 12 14 16 18]


In [81]:
a[4]

4

In [82]:
print(a[2:3])

[2]


In [83]:
a[2:4]

array([2, 3])

In [84]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Multidimensional Arrays

In [88]:
s=np.arange(20).reshape(5,4)

In [89]:
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [100]:
# acess 0,1,2,3,16,17,18,19
s[0:19:4]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19]])

In [102]:
s[1,1]

5

In [107]:
s[4,2]

18

In [108]:
s[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [109]:
s[:,2]

array([ 2,  6, 10, 14, 18])

In [123]:
s=s.flatten()
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [125]:
#print(s)
for h in s:
    print(h)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [127]:
s=np.arange(20).reshape(4,5)
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [128]:
for e in s.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [129]:
help(s.flatten())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [240]:
s=np.arange(15)

In [241]:
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [242]:
b=s
b is s

True

In [243]:
b.shape=(3,5)

In [244]:
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [245]:
s.shape

(3, 5)

In [246]:
b is s

True

In [247]:
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [248]:
b=np.arange(10)

In [249]:
c=b[:]

In [250]:
b.shape=(2,5)

In [251]:
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [252]:
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [253]:
c[3]=-3

In [254]:
print(b)
print(c)

[[ 0  1  2 -3  4]
 [ 5  6  7  8  9]]
[ 0  1  2 -3  4  5  6  7  8  9]


In [255]:
d=c[3:8]

In [256]:
print(d)

[-3  4  5  6  7]


In [257]:
d[:]=0

In [258]:
print(b)
print(c)
print(d)

[[0 1 2 0 0]
 [0 0 0 8 9]]
[0 1 2 0 0 0 0 0 8 9]
[0 0 0 0 0]


In [259]:
print(c is b)

False


In [260]:
print(c.base is b)

True


In [261]:
print(c.flags.owndata)

False


In [262]:
print(c.flags.owndata)

False


In [263]:
d=b.copy
b

array([[0, 1, 2, 0, 0],
       [0, 0, 0, 8, 9]])

In [264]:
b[:,:]=0.0
print(b)
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]]
<built-in method copy of numpy.ndarray object at 0x0000018DCADED270>


## Boolean Indexing: 

In [289]:
s=np.arange(15).reshape(3,5)

In [290]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [291]:
s[s>6]=0
s

array([[0, 1, 2, 3, 4],
       [5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [292]:
s[s==0]=-1
s

array([[-1,  1,  2,  3,  4],
       [ 5,  6, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [293]:
s==-1

array([[ True, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [302]:
h=np.arange(15).reshape(3,5)
print(h)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [303]:
h[np.logical_and(s>4,s<=7)]=0.0
h

array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [304]:
s>4

array([[False, False, False, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

## Avoiding Loops 

In [343]:
M=32
N=64
xmin=ymin=0.0
xmax=ymax=1.0

In [344]:
x=np.linspace(xmin,ymin,M,endpoint=False)
y=np.linspace(ymin,ymax,N,endpoint=False)

In [345]:
print(x.shape)
print(y.shape)

(32,)
(64,)


In [346]:
y

array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [347]:
x=np.linspace(xmin,ymin,M,endpoint=False)
y=np.linspace(ymin,ymax,N,endpoint=True)

In [348]:
print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.        , 0.01587302, 0.03174603, 0.04761905, 0.06349206,
       0.07936508, 0.0952381 , 0.11111111, 0.12698413, 0.14285714,
       0.15873016, 0.17460317, 0.19047619, 0.20634921, 0.22222222,
       0.23809524, 0.25396825, 0.26984127, 0.28571429, 0.3015873 ,
       0.31746032, 0.33333333, 0.34920635, 0.36507937, 0.38095238,
       0.3968254 , 0.41269841, 0.42857143, 0.44444444, 0.46031746,
       0.47619048, 0.49206349, 0.50793651, 0.52380952, 0.53968254,
       0.55555556, 0.57142857, 0.58730159, 0.6031746 , 0.61904762,
       0.63492063, 0.65079365, 0.66666667, 0.68253968, 0.6984127 ,
       0.71428571, 0.73015873, 0.74603175, 0.76190476, 0.77777778,
       0.79365079, 0.80952381, 0.82539683, 0.84126984, 0.85714286,
       0.87301587, 0.88888889, 0.9047619 , 0.92063492, 0.93650794,
       0.95238095, 0.96825397, 0.98412698, 1.        ])

In [349]:
import time
import numpy as np
M=32
N=64

In [350]:
x=np.linspace(0.0,1.0,M,endpoint=False)
y=np.linspace(0.0,1.0,N,endpoint=False)

In [351]:
t0=time.time()

In [352]:
g=np.zeros((M,N))

In [353]:
for i in range(M):
    for j in range(N):
        g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])

In [354]:
t1=time.time()
print("time elapsed:{} s".format(t1-t0))

time elapsed:2.46317720413208 s


In [355]:
x2d,y2d=np.meshgrid(x,y,indexing="ij")

In [356]:
print(x2d[:,0])
print(x2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [357]:
print(y2d[:,0])
print(y2d[0,:])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     0.765625 0.78125  0.796875 0.8125   0.828125 0.84375  0.859375
 0.875    0.890625 0.90625  0.921875 0.9375   0.953125 0.96875  0.984375]


In [358]:
print(x2d)

[[0.      0.      0.      ... 0.      0.      0.     ]
 [0.03125 0.03125 0.03125 ... 0.03125 0.03125 0.03125]
 [0.0625  0.0625  0.0625  ... 0.0625  0.0625  0.0625 ]
 ...
 [0.90625 0.90625 0.90625 ... 0.90625 0.90625 0.90625]
 [0.9375  0.9375  0.9375  ... 0.9375  0.9375  0.9375 ]
 [0.96875 0.96875 0.96875 ... 0.96875 0.96875 0.96875]]


In [359]:
print(y2d)

[[0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 ...
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]]


In [360]:
t0=time.time()
g2=np.sin(2.0*np.pi*x2d*y2d)

In [361]:
t1=time.time()
print("time elapsed:{}s".format(t1-t0))

time elapsed:0.27200937271118164s


## Concatenation of arrays 

In [371]:
x=np.array([1,2,3,4])
y=np.array([5,4,3,2,1])
np.concatenate([y,x])

array([5, 4, 3, 2, 1, 1, 2, 3, 4])

In [373]:
z=[9,4,6]
print(np.array([x,y,z]))

[array([1, 2, 3, 4]) array([5, 4, 3, 2, 1]) list([9, 4, 6])]


C:\Users\GIRISH~1\AppData\Local\Temp/ipykernel_712/1410538250.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array([x,y,z]))


In [377]:
grid=np.array([[50,60,70],
             [80,90,100]])

In [378]:
#concatenate along the first axis
np.concatenate([grid,grid])

array([[ 50,  60,  70],
       [ 80,  90, 100],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [379]:
#conctenate along second axis(zero-indexed)
np.concatenate([grid,grid],axis=1)

array([[ 50,  60,  70,  50,  60,  70],
       [ 80,  90, 100,  80,  90, 100]])

## Splitting of arrays

In [381]:
x=[1,2,3,4,5,5,4,3,2,1,9,4,6]
x1,x2,x3,x4=np.split(x,[3,5,8])
print(x1,x2,x3,x4)

[1 2 3] [4 5] [5 4 3] [2 1 9 4 6]


In [383]:
grid=np.arange(20).reshape((5,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [384]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


## Aggregates 

In [385]:
x=np.arange(1,15)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [386]:
np.add.reduce(x)

105

In [387]:
np.multiply.reduce(x)

1278945280

In [388]:
np.add.accumulate(x)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105], dtype=int32)

In [389]:
np.multiply.accumulate(x)

array([         1,          2,          6,         24,        120,
              720,       5040,      40320,     362880,    3628800,
         39916800,  479001600, 1932053504, 1278945280], dtype=int32)